defmodule BlackPlague do
    defmodule Equip do
    alias Zombicide.{Repo, Cards.Equipment}

    def seed() do
      Repo.insert!(%Equipment{set_id: 1, name: "Axe"})
      Repo.insert!(%Equipment{set_id: 1, name: "Axe"})
      Repo.insert!(%Equipment{set_id: 1, name: "Short Sword"})
      Repo.insert!(%Equipment{set_id: 1, name: "Sword"})
      Repo.insert!(%Equipment{set_id: 1, name: "Sword"})
      Repo.insert!(%Equipment{set_id: 1, name: "Great Sword"})
      Repo.insert!(%Equipment{set_id: 1, name: "Great Sword"})
      Repo.insert!(%Equipment{set_id: 1, name: "Hammer"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dagger"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dagger"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dagger"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dagger"})
      Repo.insert!(%Equipment{set_id: 1, name: "Repeating Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Repeating Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Short Bow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Hand Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Hand Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Longbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Longbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Crossbow"})
      Repo.insert!(%Equipment{set_id: 1, name: "Speed"})
      Repo.insert!(%Equipment{set_id: 1, name: "Repulse"})
      Repo.insert!(%Equipment{set_id: 1, name: "Fireball"})
      Repo.insert!(%Equipment{set_id: 1, name: "Fireball"})
      Repo.insert!(%Equipment{set_id: 1, name: "Death Strike"})
      Repo.insert!(%Equipment{set_id: 1, name: "Death Strike"})
      Repo.insert!(%Equipment{set_id: 1, name: "Mana Blast"})
      Repo.insert!(%Equipment{set_id: 1, name: "Healing"})
      Repo.insert!(%Equipment{set_id: 1, name: "Invisibility"})
      Repo.insert!(%Equipment{set_id: 1, name: "Lightning Bolt"})
      Repo.insert!(%Equipment{set_id: 1, name: "Lightning Bolt"})
      Repo.insert!(%Equipment{set_id: 1, name: "Shield"})
      Repo.insert!(%Equipment{set_id: 1, name: "Shield"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plate Armor"})
      Repo.insert!(%Equipment{set_id: 1, name: "Chainmail Armor"})
      Repo.insert!(%Equipment{set_id: 1, name: "Chainmail Armor"})
      Repo.insert!(%Equipment{set_id: 1, name: "Leather Armor"})
      Repo.insert!(%Equipment{set_id: 1, name: "Leather Armor"})
      Repo.insert!(%Equipment{set_id: 1, name: "Torch"})
      Repo.insert!(%Equipment{set_id: 1, name: "Torch"})
      Repo.insert!(%Equipment{set_id: 1, name: "Torch"})
      Repo.insert!(%Equipment{set_id: 1, name: "Torch"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dragon Bile"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dragon Bile"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dragon Bile"})
      Repo.insert!(%Equipment{set_id: 1, name: "Dragon Bile"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Arrows"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Arrows"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Arrows"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Bolts"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Bolts"})
      Repo.insert!(%Equipment{set_id: 1, name: "Plenty of Bolts"})
      Repo.insert!(%Equipment{set_id: 1, name: "Apples"})
      Repo.insert!(%Equipment{set_id: 1, name: "Apples"})
      Repo.insert!(%Equipment{set_id: 1, name: "Water"})
      Repo.insert!(%Equipment{set_id: 1, name: "Water"})
      Repo.insert!(%Equipment{set_id: 1, name: "Salted Meat"})
      Repo.insert!(%Equipment{set_id: 1, name: "Salted Meat"})
      Repo.insert!(%Equipment{set_id: 1, name: "Aaahh!! (Zombie)"})
      Repo.insert!(%Equipment{set_id: 1, name: "Aaahh!! (Zombie)"})
      Repo.insert!(%Equipment{set_id: 1, name: "Aaahh!! (Zombie)"})
      Repo.insert!(%Equipment{set_id: 1, name: "Aaahh!! (Zombie)"})
    end
  end
end
