defmodule BlackPlague do
    defmodule Equip do
    alias Zombicide.Cards

    def seed() do
      Cards.create_equipment(1, %{name: "Axe"})
      Cards.create_equipment(1, %{name: "Axe"})
      Cards.create_equipment(1, %{name: "Short Sword"})
      Cards.create_equipment(1, %{name: "Sword"})
      Cards.create_equipment(1, %{name: "Sword"})
      Cards.create_equipment(1, %{name: "Great Sword"})
      Cards.create_equipment(1, %{name: "Great Sword"})
      Cards.create_equipment(1, %{name: "Hammer"})
      Cards.create_equipment(1, %{name: "Dagger"})
      Cards.create_equipment(1, %{name: "Dagger"})
      Cards.create_equipment(1, %{name: "Dagger"})
      Cards.create_equipment(1, %{name: "Dagger"})
      Cards.create_equipment(1, %{name: "Repeating Crossbow"})
      Cards.create_equipment(1, %{name: "Repeating Crossbow"})
      Cards.create_equipment(1, %{name: "Short Bow"})
      Cards.create_equipment(1, %{name: "Hand Crossbow"})
      Cards.create_equipment(1, %{name: "Hand Crossbow"})
      Cards.create_equipment(1, %{name: "Longbow"})
      Cards.create_equipment(1, %{name: "Longbow"})
      Cards.create_equipment(1, %{name: "Crossbow"})
      Cards.create_equipment(1, %{name: "Crossbow"})
      Cards.create_equipment(1, %{name: "Speed"})
      Cards.create_equipment(1, %{name: "Repulse"})
      Cards.create_equipment(1, %{name: "Fireball"})
      Cards.create_equipment(1, %{name: "Fireball"})
      Cards.create_equipment(1, %{name: "Death Strike"})
      Cards.create_equipment(1, %{name: "Death Strike"})
      Cards.create_equipment(1, %{name: "Mana Blast"})
      Cards.create_equipment(1, %{name: "Healing"})
      Cards.create_equipment(1, %{name: "Invisibility"})
      Cards.create_equipment(1, %{name: "Lightning Bolt"})
      Cards.create_equipment(1, %{name: "Lightning Bolt"})
      Cards.create_equipment(1, %{name: "Shield"})
      Cards.create_equipment(1, %{name: "Shield"})
      Cards.create_equipment(1, %{name: "Plate Armor"})
      Cards.create_equipment(1, %{name: "Chainmail Armor"})
      Cards.create_equipment(1, %{name: "Chainmail Armor"})
      Cards.create_equipment(1, %{name: "Leather Armor"})
      Cards.create_equipment(1, %{name: "Leather Armor"})
      Cards.create_equipment(1, %{name: "Torch"})
      Cards.create_equipment(1, %{name: "Torch"})
      Cards.create_equipment(1, %{name: "Torch"})
      Cards.create_equipment(1, %{name: "Torch"})
      Cards.create_equipment(1, %{name: "Dragon Bile"})
      Cards.create_equipment(1, %{name: "Dragon Bile"})
      Cards.create_equipment(1, %{name: "Dragon Bile"})
      Cards.create_equipment(1, %{name: "Dragon Bile"})
      Cards.create_equipment(1, %{name: "Plenty Of Arrows"})
      Cards.create_equipment(1, %{name: "Plenty Of Arrows"})
      Cards.create_equipment(1, %{name: "Plenty Of Arrows"})
      Cards.create_equipment(1, %{name: "Plenty Of Bolts"})
      Cards.create_equipment(1, %{name: "Plenty Of Bolts"})
      Cards.create_equipment(1, %{name: "Plenty Of Bolts"})
      Cards.create_equipment(1, %{name: "Apples"})
      Cards.create_equipment(1, %{name: "Apples"})
      Cards.create_equipment(1, %{name: "Water"})
      Cards.create_equipment(1, %{name: "Water"})
      Cards.create_equipment(1, %{name: "Salted Meat"})
      Cards.create_equipment(1, %{name: "Salted Meat"})
      Cards.create_equipment(1, %{name: "Aaahh!! (Zombie)"})
      Cards.create_equipment(1, %{name: "Aaahh!! (Zombie)"})
      Cards.create_equipment(1, %{name: "Aaahh!! (Zombie)"})
      Cards.create_equipment(1, %{name: "Aaahh!! (Zombie)"})
    end
  end
end
